# Generated by Django 4.2.11 on 2026-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_punch_spans_next_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(blank=True, help_text='Assigned shift name (e.g. General Shift)', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_from',
            field=models.TimeField(blank=True, help_text='Shift start time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_to',
            field=models.TimeField(blank=True, help_text='Shift end time', null=True),
        ),
    ]
