# Generated by Django 4.2.11 on 2026-02-12 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_shift_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='days_present',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days marked Present in the month'),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total hours worked in the month', max_digits=8),
        ),
    ]
