# Generated by Django 4.2.11 on 2026-02-14 06:34

from django.db import migrations, models


def set_super_admin(apps, schema_editor):
    Admin = apps.get_model('core', 'Admin')
    Admin.objects.filter(pk=1).update(role='super_admin')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salary_hours_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='access',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('dept_admin', 'Department Admin')], default='dept_admin', max_length=20),
        ),
        migrations.RunPython(set_super_admin, noop),
    ]
