# Generated by Django 4.2.11 on 2026-02-14 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('month', models.PositiveSmallIntegerField(help_text='Salary month this advance is for')),
                ('year', models.PositiveIntegerField(help_text='Salary year this advance is for')),
                ('date_given', models.DateField(blank=True, help_text='Date advance was given', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salary_advances',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
    ]
