# Generated by Django 4.2.11 on 2026-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_penalty_and_fixed_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(default='smtp.gmail.com', help_text='e.g. smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveSmallIntegerField(default=587, help_text='Usually 587 for TLS')),
                ('auth_username', models.CharField(blank=True, help_text='SMTP login email', max_length=254)),
                ('auth_password', models.CharField(blank=True, help_text='App password or account password', max_length=255)),
                ('force_sender', models.CharField(blank=True, help_text='From address (optional, defaults to auth_username)', max_length=254)),
                ('error_logfile', models.CharField(blank=True, help_text='Path to error log file', max_length=255)),
                ('debug_logfile', models.CharField(blank=True, help_text='Path to debug log file', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Use this config when sending email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email SMTP config',
                'verbose_name_plural': 'Email SMTP configs',
                'db_table': 'email_smtp_config',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Week off', 'Week off'), ('Holiday', 'Holiday')], default='Active', max_length=20),
        ),
    ]
